// 4 types of constrcutors: default, parameterized, copy, move
// 1. default: automatically generated by the compiler if not programmer-defined. not generated if there is a programmer-defined constructor

#include <iostream>
using namespace std;

class A {
public:
    int val;
    unique_ptr<int> p;
    
  	// 2. Parameterized Constructor
    A(int x) {
        val = x;
    }
    // if we still want a default constructor when we already explicitly define a constructor, we need to define
    // the default constructor explicitly, as the compiler will not automatically generate it any more
    A(){
        cout << "Default constructor called." << endl;
    }

    // 3. copy constructor: initializes an object using another object of the same class by taking the references
    // compiler provides an implicit copy constructor
    // and it will always be created if there is no explicit copy constructor OR explicit move constructor(only these two types will affect implicit copy constructor)
    A(A& a) {
        val = a.val;
    }
    
};


struct Holder {
    unique_ptr<int> p;
    // 4. Move constructor: constructs the object from the already existing objects
    // but transfers the ownership of the already created object to the new object without creating extra copies
    // by using std::move
    // the compiler automatically generates a move constructor if not programmer-defined, AND there is no declared copy constructors/move constructors/destructors
    Holder(unique_ptr<int> q) : p(std::move(q)) {
        cout << "move constructor: p.get() = " << p.get() << "\n";
    }
};

int main() {
  
  	// Creating object with a parameter
    A a(10);
    cout << a.val << endl;
    A a1; // test if the default constructor works

    // creating another object from a1
    A a2(a1);
    cout << "a2: " << a2.val << endl;
    cout << "&a2: " << &a2 << endl;
    cout << "&a1: " << &a1 << endl;

    // example of move constructor
    auto up = make_unique<int>(42);
    cout << "before move: up.get() = " << up.get() << " value=" << *up << "\n";

    Holder h(std::move(up));         // transfer ownership of the int
    cout << "after  move: up.get() = " << up.get() << " (null means moved-from)\n";
    cout << "holder owns: " << h.p.get() << " value=" << *h.p << "\n";

    return 0;
}

/* Characteristics of constructors
1. mostly declared as public member, though they can be declared as private
2. do not return values(hence do not have a return type)
3. can be overloaded(can declare multiple constructors)
*/